[workspace]
members = ["day01", "day02", "day03", "day04", "day05", "meta"]

[workspace.dependencies]
aoc-traits = { git = "https://github.com/dkales/adventofcode2023-leaderboard", rev = "ac544663758c2dca2ee892fd7ab59419999350dc" }
